### ISSUE TITLE
question about clustering performance on YTF dataset

### ISSUE THREAD

**Issue by GeKeShi** [herandy/DEPICT#2]
hello! i've attempted to run your code on the YTF dataset, but the clustering accuracy i can achieved is 56%, i wonder i missed some important process in the code running, could you show your running detail or give me some advice, thank you!

**Comment by herandy** [comment]
Your preprocessing for the dataset is probably different. We are using the exact same version that the JULE [paper](https://github.com/jwyang/JULE-Torch) also uses. You can download it from their [google drive page](https://drive.google.com/drive/folders/0B9J-9A2jotGRT25vSDhUWTQxVWs).
