### ISSUE TITLE
DEPICT for text classification?

### ISSUE THREAD

**Issue by TheodoreGalanos** [herandy/DEPICT#4]
Hello!

First of all thanks for sharing this work, it's amazing!

I have a bit of a peculiar question I guess. Do you think DEPICT could easily be adapted to fit to text classification. I'm really not trained in the field so my simple mind only tells me change Conv layers to 1D and adjust their options and you're good to go, but of course it has to be a whole lot more than that.

Was wondering if you had ever thought of this application and if you think it would work. If not the specific model, then a similar approach to text classification. Seems to fit in the efforts of classifying  documents that can take one out of n possible sentiment target values.

Would love to hear your thoughts!

Kind regards,
Theodore.

**Comment by herandy** [comment]
For classification you probably could find models specifically for that task. This could be adapted but I think it would be better suited for unsupervised learning like what we have done in the paper, meaning that your knowledge about the data is vastly more limited compared to supervised learning (No labels). I think there are a lot of models for classification and specifically text classification, LSTMs as well as CNN models.

**Comment by TheodoreGalanos** [comment]
Hi @herandy 

Thanks a lot for your answer, yeah I was mostly thinking of this in an unsupervised manner. So even if I had the labels, I could use the model's clustering results as an additional input to classification process. The labels we have would mostly help in defining the clusters.

You are right of course, there are loads of other models and I'm using some of them. But none of the has this clustering kind of approach, that could be useful.

But yeah, I'm sure this might mean a complete rehaul even if it is possible, but was worth the ask!

Thanks for the inputs!

Kind regards,
Theodore.
